ARTICLE_DB_PATH : /opt/shichenh/articles_embedding.json
AUDIO_DIRECTORY : /opt/shichenh/tts_data/openai_tts_data/data

tts_english:
  model_name: 'tts_models/en/ljspeech/tacotron2-DDC'

tts_chinese:
  model_name: 'tts_models/zh-CN/baker/tacotron2-DDC-GST'
